### ISSUE TITLE
ToPdf Cli Package

### ISSUE THREAD

**Issue by conneroisu** [conneroisu/dotfiles#53]
Use pandoc to export markdown to pdf with custom styling,

The styling css with be kept in the nix store and used with the flag `--css` to visually customize the output.
Additionally, the shell application generated from nix should use the `--mathjax` flag to allow for mathjax.
There may have to be an extra step for converting from html to pdf. 

# `default.nix`

It might be nice to have a --preview flage that can be passed in addition to the input markdown file.
```nix
{
  delib,
  pkgs,
  ...
}: let
  inherit (delib) singleEnableOption;
  program =
    pkgs.writeShellScriptBin "dx" ''
      ${pkgs.pandoc}/bin/pandoc --css ${./toPDF.css} --mathjax '';
in
  delib.module {
    name = "programs.dx";

    options = singleEnableOption false;

    nixos.ifEnabled = {
      environment.systemPackages = [
        program
      ];
    };
    darwin.ifEnabled = {
      environment.systemPackages = [
        program
      ];
    };
  }
```
# Constants (Psudeo Go)
```bash
pandoc input.md -o output.pdf \
  --pdf-engine=xelatex \
  --template=eisvogel \
  --highlight-style=kate \
  -V mainfont="Inter" \
  -V monofont="JetBrains Mono" \
  -V fontsize=11pt \
  -V geometry:margin=1in \
  -V linkcolor=blue
```
```go
type PDFEngine string
type Template string
type HighlightStyle string
```
# CSS Styling `styles.css`

```css
html {
  font-size: 100%;
  overflow-y: scroll;
  -webkit-text-size-adjust: 100%;
  -ms-text-size-adjust: 100%;
}

body {
  color: #444;
  font-family: Georgia, Palatino, 'Palatino Linotype', Times, 'Times New Roman', serif;
  font-size: 12px;
  line-height: 1.7;
  padding: 1em;
  margin: auto;
  max-width: 42em;
  background: #fefefe;
}

a {
  color: #0645ad;
  text-decoration: none;
}

a:visited {
  color: #0b0080;
}

a:hover {
  color: #06e;
}

a:active {
  color: #faa700;
}

a:focus {
  outline: thin dotted;
}

*::-moz-selection {
  background: rgba(255, 255, 0, 0.3);
  color: #000;
}

*::selection {
  background: rgba(255, 255, 0, 0.3);
  color: #000;
}

a::-moz-selection {
  background: rgba(255, 255, 0, 0.3);
  color: #0645ad;
}

a::selection {
  background: rgba(255, 255, 0, 0.3);
  color: #0645ad;
}

p {
  margin: 1em 0;
}

img {
  max-width: 100%;
}

h1, h2, h3, h4, h5, h6 {
  color: #111;
  line-height: 125%;
  margin-top: 2em;
  font-weight: normal;
}

h4, h5, h6 {
  font-weight: bold;
}

h1 {
  font-size: 2.5em;
}

h2 {
  font-size: 2em;
}

h3 {
  font-size: 1.5em;
}

h4 {
  font-size: 1.2em;
}

h5 {
  font-size: 1em;
}

h6 {
  font-size: 0.9em;
}

blockquote {
  color: #666666;
  margin: 0;
  padding-left: 3em;
  border-left: 0.5em #EEE solid;
}

hr {
  display: block;
  height: 2px;
  border: 0;
  border-top: 1px solid #aaa;
  border-bottom: 1px solid #eee;
  margin: 1em 0;
  padding: 0;
}

pre, code, kbd, samp {
  color: #000;
  font-family: monospace, monospace;
  _font-family: 'courier new', monospace;
  font-size: 0.98em;
}

pre {
  white-space: pre;
  white-space: pre-wrap;
  word-wrap: break-word;
}

b, strong {
  font-weight: bold;
}

dfn {
  font-style: italic;
}

ins {
  background: #ff9;
  color: #000;
  text-decoration: none;
}

mark {
  background: #ff0;
  color: #000;
  font-style: italic;
  font-weight: bold;
}

sub, sup {
  font-size: 75%;
  line-height: 0;
  position: relative;
  vertical-align: baseline;
}

sup {
  top: -0.5em;
}

sub {
  bottom: -0.25em;
}

ul, ol {
  margin: 1em 0;
  padding: 0 0 0 2em;
}

li p:last-child {
  margin-bottom: 0;
}

ul ul, ol ol {
  margin: .3em 0;
}

dl {
  margin-bottom: 1em;
}

dt {
  font-weight: bold;
  margin-bottom: .8em;
}

dd {
  margin: 0 0 .8em 2em;
}

dd:last-child {
  margin-bottom: 0;
}

img {
  border: 0;
  -ms-interpolation-mode: bicubic;
  vertical-align: middle;
}

figure {
  display: block;
  text-align: center;
  margin: 1em 0;
}

figure img {
  border: none;
  margin: 0 auto;
}

figcaption {
  font-size: 0.8em;
  font-style: italic;
  margin: 0 0 .8em;
}

table {
  margin-bottom: 2em;
  border-bottom: 1px solid #ddd;
  border-right: 1px solid #ddd;
  border-spacing: 0;
  border-collapse: collapse;
}

table th {
  padding: .2em 1em;
  background-color: #eee;
  border-top: 1px solid #ddd;
  border-left: 1px solid #ddd;
}

table td {
  padding: .2em 1em;
  border-top: 1px solid #ddd;
  border-left: 1px solid #ddd;
  vertical-align: top;
}

.author {
  font-size: 1.2em;
  text-align: center;
}

@media only screen and (min-width: 480px) {
  body {
    font-size: 14px;
  }
}
@media only screen and (min-width: 768px) {
  body {
    font-size: 16px;
  }
}
@media print {
  * {
    background: transparent !important;
    color: black !important;
    filter: none !important;
    -ms-filter: none !important;
  }

  body {
    font-size: 12pt;
    max-width: 100%;
  }

  a, a:visited {
    text-decoration: underline;
  }

  hr {
    height: 1px;
    border: 0;
    border-bottom: 1px solid black;
  }

  a[href]:after {
    content: " (" attr(href) ")";
  }

  abbr[title]:after {
    content: " (" attr(title) ")";
  }

  .ir a:after, a[href^="javascript:"]:after, a[href^="#"]:after {
    content: "";
  }

  pre, blockquote {
    border: 1px solid #999;
    padding-right: 1em;
    page-break-inside: avoid;
  }

  tr, img {
    page-break-inside: avoid;
  }

  img {
    max-width: 100% !important;
  }

  @page :left {
    margin: 15mm 20mm 15mm 10mm;
}

  @page :right {
    margin: 15mm 10mm 15mm 20mm;
}

  p, h2, h3 {
    orphans: 3;
    widows: 3;
  }

  h2, h3 {
    page-break-after: avoid;
  }
}

```

defaults.yaml
```yaml
---
# Document metadata
title-meta: "${title}"
author-meta: "${author}"
lang: en-US

# PDF generation settings
pdf-engine: xelatex
template: eisvogel

# Typography matching Obsidian
variables:
  mainfont: "Inter"
  sansfont: "Inter"  
  monofont: "JetBrains Mono"
  fontsize: 11pt
  linestretch: 1.15
  geometry: margin=1in
  
  # Colors similar to Obsidian
  linkcolor: "#705dcf"
  urlcolor: "#705dcf"
  citecolor: "#705dcf"
  
  # Document structure
  toc: true
  toc-depth: 3
  numbersections: true
  secnumdepth: 3
  
  # Code blocks
  highlight-style: kate
  code-block-font-size: \small
  listings: true
  
  # Eisvogel template specific
  titlepage: true
  titlepage-color: "435488"
  titlepage-text-color: "FFFFFF"
  footnotes-pretty: true
  
# Filters and processing
filters:
  - pandoc-crossref
  - filters/obsidian-links.lua
  - filters/obsidian-callouts.lua
  
citeproc: true
---
```

# Lua Filter (Allows support for obsidian syntax):

```lua
-- obsidian-complete.lua
-- Handles wikilinks, embeds, callouts, and tags

-- Handle [[wikilinks]] and [[link|alias]]
function Link(el)
  if el.title == "wikilink" then
    -- Extract alias if present
    local target = el.target
    local alias = el.content
    
    if target:match("|") then
      local parts = {}
      for part in target:gmatch("[^|]+") do
        table.insert(parts, part)
      end
      target = parts[1]
      if #parts > 1 then
        alias = pandoc.Str(parts[2])
      end
    end
    
    -- Convert to standard link
    return pandoc.Link(alias, target .. ".html", "", {class="internal-link"})
  end
  return el
end

-- Handle ![[embeds]]
function Image(el)
  if el.src:match("^!%[%[") then
    local embed = el.src:match("!%[%[(.+)%]%]")
    if embed then
      -- Check if it's an image
      if embed:match("%.png$") or embed:match("%.jpg$") or embed:match("%.jpeg$") then
        return pandoc.Image(el.caption, embed, el.title, el.attr)
      else
        -- It's a note embed - read and include content
        local file = io.open(embed .. ".md", "r")
        if file then
          local content = file:read("*all")
          file:close()
          return pandoc.Div(pandoc.read(content).blocks, {class="embedded-note"})
        end
      end
    end
  end
  return el
end

-- Handle callouts: > [!note] Title
function BlockQuote(el)
  local first = el.content[1]
  if first and first.t == "Para" then
    local first_str = pandoc.utils.stringify(first)
    local callout_type, title = first_str:match("^%[!(%w+)%]%s*(.*)$")
    
    if callout_type then
      -- Remove the callout marker from content
      table.remove(el.content, 1)
      if title and title ~= "" then
        table.insert(el.content, 1, pandoc.Header(6, title))
      end
      
      -- Return styled div
      return pandoc.Div(el.content, {
        class = "callout callout-" .. callout_type:lower()
      })
    end
  end
  return el
end

-- Handle #tags
function Str(el)
  local tag = el.text:match("^#([%w%-_/]+)$")
  if tag then
    return pandoc.Span(el.text, {class="tag"})
  end
  return el
end
```
