### ISSUE TITLE
add cache action from flakehub

### ISSUE THREAD

**Issue by conneroisu** [conneroisu/dotfiles#8]
ex:
      - uses: DeterminateSystems/flakehub-cache-action@main

```yaml name="action.yml"
jobs:
  check:
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: true
      - uses: DeterminateSystems/flakehub-cache-action@main
```
